theme: jekyll-theme-minimal
title: Learning Bulgarian and Italian through English
highlighter: rouge

exclude: ['CNAME', 'CONTRIBUTING.md', 'LICENSE', 'README.md']

gems:
    - jekyll-sitemap

defaults:
    -
      scope:
          path: ""
      values:
          sitemap: false
